### ISSUE TITLE
`/welcome` Should Trigger Help Message for the `/welcome` Command

### ISSUE THREAD

**Issue by BethanyG** [codebuddiesdotorg/greetbot#1]
`/welcome` - without a sub-command or @username should trigger a help message on how to use the `/welcome` command.  Something along the lines of:
_____________________________________________________________________
### `/welcome` is a command to greet users with the CB welcome message & Code of Conduct.
- `/welcome test`:  Sends a test welcome message as a DM to the user who typed it.  
- `/welcome [resource name]`:  Sends "getting started in [resource x]" message as a DM to the user who typed it.
- `/welcome [command] @username`:  Sends the result of the command (test, resource, etc.) as a DM to the user specified.
_____________________________________________________________________
Currently, the bot throws a 503 error, because there is no explicit route or message attached to `/welcome` by itself.

**Comment by BethanyG** [comment]
THANK YOU @railsstudent for a most excellent fix.  Merged and added to the refactored code as well.

**Comment by railsstudent** [comment]
With pleasure.
