### ISSUE TITLE
Add `/welcome` post + Channel Name To Post Welcome Message in a Specific Channel

### ISSUE THREAD

**Issue by BethanyG** [codebuddiesdotorg/greetbot#2]
It would be nice to have the ability to re-post the welcome message in **#start_here** - or any other channel that needs it, on demand.  I think this is going to require:

1.  Formatting the welcome message & the Code of Conduct as **Slack Posts**, minus the [accept] button (we have them - they just need to be formally formatted and put in the repo as assets).
2. Ability to parse out a channel name in the welcome command, if it exists in the message sent from Slack
3.   New endpoint functionality for the `post` command to have the message sent as a Slack Post and not the DM-style message.
4.  Change to the message sending logic, so that having a channel name triggers a message post to the specified public Channel ID instead of the DM Channel ID.

**Comment by railsstudent** [comment]
I have some experience in slack posting. I can try to do it in the weekend.

**Comment by angelocordon** [comment]
@railsstudent is the `ready for review` tag for #25? Just want to clarify if this issue is `in progress` or `ready for review`. They can't be both.

**Comment by stain88** [comment]
Fixed in #31
