### ISSUE TITLE
Separate learning resources and projects / tutorials

### ISSUE THREAD

**Issue by robinfla** [codebuddiesdotorg/greetbot#23]
Talking about resources, two different concepts actually emerge: theory & practice. While practice with exercises is a necessary complement to theory, practice with tutorials or projects, is a bit different. 

It should be somewhat differentiated along the way. Ideally, a user would be prompted resources with ```/resources``` but we could add additional options for instance, ```/resources projects```

However, we should also add warnings for beginners because projets and tutorials can be complex and challenging if the syntax and theory is not well understood.

**Comment by stain88** [comment]
i would suggest splitting out into a `/projects` command, as there's probably enough parsing going on in `/resources` already

**Comment by angelocordon** [comment]
+1 with @stain88 - I think this can be revisited as a `/projects` feature

**Comment by BethanyG** [comment]
Going to re-file this as **Add New `/projects` Endpoint**, so we can discuss/plan/assign accordingly.

**Comment by BethanyG** [comment]
I am going to close this in favor of #58.  Please feel free to re-open if I've missed something.
