### ISSUE TITLE
Add `/resource` Slash Endpoint for Sending Various Resources to Users

### ISSUE THREAD

**Issue by BethanyG** [codebuddiesdotorg/greetbot#4]
Rather than have all the commands under `/welcome`, suggest we add a different "slash command" to the greetbot around sending/asking for resources.  This would be a new route/endpoint.  The idea would be to have `/resources` respond with a DM to a channel or user with CB "recommended" resources.  Something along the lines of :
__
`/resources` [name of topic] [level] [_channel_] [_user_]
__
So -- `/resources python beginner @username` would DM a specific user beginner-level resources for Python.

Current thoughts:
1.  `/resources` would result in a help message
2.  `/resources list` would list available resources
3.  `/resources python` would DM the requestor with python resources (default would be beginner level, unless otherwise specified)
4.  `/resources python beginner @username` would DM the specified user with beginner python resources.
5. `/resources python beginner #channelname` would send a Slack Post of the beginner python resources to the channel specified.
6.  `/resources python beginner #channelname @username` would do both #4 and #5 (and would only be a nice to have).

**Comment by BethanyG** [comment]
Starter list of things we'd `/resources` (Beginning / Intermediate / Advanced):

- Web Dev
- FullStack Dev
- Databases/SQL
- ~Python~ **(done)**
- ~JavaScript~ **(done)**
- HTML
- CSS
- Ruby
- Go-lang
- Data Science

**Comment by railsstudent** [comment]
I probably do it phases, submit one PR for each command.
Will start after studying the current codebase.

**Comment by BethanyG** [comment]
Totally agree - a phased approach would be the best.  Just getting the resources, and deciding on formats, etc. is a whole project itself.  

See https://github.com/codebuddies/greetbot/projects/4 & https://github.com/codebuddies/greetbot/projects/3

Recommend we open some issues or sub-issues around which commands we'd like to implement -
 and when.  That way, each can be on the board, and we can track their progress.  

In addition, recommend we start parsing out topic/language _messages_  for those commands into their own issue set that can be assigned separate from the  code that adds the endpoints/commands.  That way, we can have some people focusing on the messages & formats, and others (who are more interested in node & JS) focusing on wiring things up.

**As a side note to that:**  Slack's messages are required to be in this slightly weird markdown format.  It's _markdown_, but an adapted sub-set of markdown.  And to get that to render with `JSON.stringify` requires some special escapes, too.  So - I can't this morning, but later today I will take a shot at putting together some documentation so that people formatting/working on the _content_ of messages know what to do.

I also would like to get a **template** or several templates going for these messages - that way, someone could theoretically sit down and crank through a bunch with less effort.

@angelocordon, @robinfla, @lpatmo, @stain88, @rmorabia   - please weigh in with thoughts, concerns, ideas.  _Thank you!_  Also please feel free to add/open new issues around this, so that we have a to-do list.

**Comment by stain88** [comment]
Proposal:
Resources are hosted in `data/slash/resources/resources.yml`, with general format:
```yaml
- resources:
  - name: "resource1"
    level: "beginner"
    language: "python"
  - name: "resource2"
    level: "advanced"
    language: "webdev"
```
etc. Easy to add to, no need for sorting, can easily add other keys if needed (like paid, blog, book...)
We can then split `req.body.text` on spaces, grab username/channel with the same regex as welcome, and if what's left isn't `list`, grab the data from yaml and filter on all the keywords. List returns all names/languages/whatever we want it to return.

**Comment by railsstudent** [comment]
if using yaml, do we need to convert yaml to JSON format and nodejs code access the key/value in the JSON object.

**Comment by BethanyG** [comment]
@stain88 -- excellent suggestions!  I may have complexified things  a tad too much with the refactor....

The way things are now, all the parsing logic for the incoming `/slash` POST  lives in **util/incomingParser.js.**  It gets called by **src/routes/endpoints/welcome/welcome.js** to deal with the incoming request message. 

 My thought there being that no matter the POST to `/slash (whatever)`  we always hand back **{target_user, target_channel, action, payload}**.  What the particular `/slash` endpoint logic does with them is then up to whomever is coding that endpoint.   

So - with the addition of `/resources` --> we'd use the exact same **incomingParser.js**....BUT.... we'd change the API (and so the logic in welcome.js slightly as well) to hand back a **_list_** of actions that the endpoint would then unpack.

...does that make sense?  Or does it make more sense to do a second incoming parser for `/resources`?  I am open to any and all ideas.  😀

**Comment by BethanyG** [comment]
...as for the .yaml file.  That certainly would be efficient on one level, and mimics what we'd more or less do for a DB.  I need help though in thinking through what the rest of it looks like.  Here is what we currently have:

1)  POSTed Message comes into a `/index.js`, and gets routed to, say  **/routes/endpoints/welcome.js**
2)  In **welcome.js**, a call goes to **/util/incomingParser.js**, to parse the POST for _command_, _user_, etc.
3)  Once the POST parse result comes back, the **welcome.js endpoint** triggers the method that sends outgoing messages one or more times.
4)  The sendMessage method looks in **/routes/data/slash/welcome/slashWelcome.js** (or slashHelp.js or whatever) for the JSON and Markdown content of the outgoing message to send, then does a `stringify()` & sends it.

...because the messages get formatted in this funkalicous  combo of JSON and Slack markdown (see the slashWelcome.js file for all it's glory)..... I'm just not sure I want to stick all of that mess in a single file.  But again - as I have said before, I am an over-thinker.  So - please please chime in with suggestions.  I've also attached a sample mock-up of an outgoing message, so you can see in general sort of the type of formatting we're talking about:


<img width="736" alt="screen shot 2018-03-03 at 7 09 29 pm" src="https://user-images.githubusercontent.com/5923094/36941903-bd93c138-1f1a-11e8-9921-72a1e7e56cfd.png">

**Comment by rmorabia** [comment]
I may be old-school, but I still think we need a human-written version of each message because I think the information design will be different for each one. 

It's hard to say a beginner `/resources` message with general links will be similar to an intermediate `/resources` message with sub-categories for frameworks, concepts, etc..

**Comment by stain88** [comment]
@railsstudent: yes, but that can easily be done with `require('yamljs')`. I also think it's a more versatile file type, and would be easier to transfer to the db once that's up and running.
@BethanyG: yeah, probably could (and arguably should) use the same parser - never really looked beyond what we were fixing the other day as to what it actually does.
@rmorabia: agree, to some extent, but this can be reviewed once the resources are "finalised" and we have a better idea of what we're dealing with. But we can start with an initial template of `Here are some {level} {language} resources` etc..

**Comment by BethanyG** [comment]
**Beginner JS First Round::**

<img width="605" alt="screen shot 2018-03-09 at 2 44 43 am" src="https://user-images.githubusercontent.com/5923094/37204364-75313658-2345-11e8-85fb-12ea8db4b833.png">

**Comment by BethanyG** [comment]
**Intermediate JS First Round:**

<img width="653" alt="screen shot 2018-03-09 at 3 14 05 am" src="https://user-images.githubusercontent.com/5923094/37205477-c637752c-2349-11e8-8531-3cef69e85e09.png">

**Comment by BethanyG** [comment]
**Advanced JS First Draft**

![screen shot 2018-03-09 at 4 55 45 am](https://user-images.githubusercontent.com/5923094/37208598-c05655bc-2356-11e8-9713-ea0b2a07cc6b.png)

**Comment by BethanyG** [comment]
I am going to close this in favor of opening separate issues for each resource topic added.  The base work of adding the endpoint and related functionality has been completed.
