### ISSUE TITLE
Rewrite incomingParser.js to Accommodate Arbitrary Numbers of Commands & Targets

### ISSUE THREAD

**Issue by BethanyG** [codebuddiesdotorg/greetbot#43]
As part of the support for Issue #4, we need to change the incomingParser.js to pull out more than one command/@username/ or #channnelaname at a time, & return those parameters as _lists_ inside the object that the endpoint receives. 

- [x] Parse out multiple commands
- [x] Parse out multiple @users 
- [x] Parse out multiple #channelnames 
- [x] Change welcome.js to deal with new parameters
- [x] Change resources.js to deal with new parameters

**Comment by stain88** [comment]
So, the last 4 should be done, within the current message setup.
Parsing out multiple commands, to be looked at once we have some dummy data for `/resources`

**Comment by BethanyG** [comment]
_excellent!_

**Comment by stain88** [comment]
Think we're ready...

**Comment by stain88** [comment]
Good to close?

**Comment by BethanyG** [comment]
Closing.  _excellent work!_  THANK YOU.
