### ISSUE TITLE
Change YAML Util File to Glob the Multiple YAML Resource Files Into One File

### ISSUE THREAD

**Issue by BethanyG** [codebuddiesdotorg/greetbot#56]
In support of #53, #54, and #55 - we'll need to blob all the individual YAML files into one for ease of processing and filtering.

**Comment by stain88** [comment]
![glob](http://31.media.tumblr.com/b65f39c9f4b433cf18415a523d7ce3fe/tumblr_nnq8h9jDHE1so564ko1_500.gif)
