### ISSUE TITLE
Add Testing Framework

### ISSUE THREAD

**Issue by BethanyG** [codebuddiesdotorg/greetbot#7]
Need to add a testing framework for the generating and running of automated tests.

**Comment by angelocordon** [comment]
Working on this separately, will bring it over once I have something more stable. 

Currently experimenting with Mocha, Chai and Supertest (seem like these are the go to testing frameworks for ExpressJS apps).

**Comment by angelocordon** [comment]
#61

**Comment by angelocordon** [comment]
Currently reviewing @stain88's PR #61

**Comment by stain88** [comment]
Good to close now that #61 is merged?
