### ISSUE TITLE
Documentation First Pass

### ISSUE THREAD

**Issue by BethanyG** [codebuddiesdotorg/greetbot#8]
Need to put together some documentation for both usage and maintenance.

**Comment by BethanyG** [comment]
**SOME NOTES**
- need to add Glitch.com links, screenshots,  and a brief How-to for users interested in the platform.
- need to add links to the Slack API docs, and highlight relevant bits for newbies (especially the `event.users.is_bot` property, and bot users in general.
- might want to consider a Docker container or Docker compose file for users who'd like to do the whole NGROK thing, but are a little lost.
- need to add links to the branching screenshot that @angelocordon posted - that should be our working model going forward
- should add a little "how we treat one another on staging" list - not that we have an issue, just that we should remind people to play nice in the sandbox

**Comment by angelocordon** [comment]
Depending on how #42 goes, maybe we can close this issue? I think after that, we'd be open for a second pass on the docs on the next release.

**Comment by angelocordon** [comment]
#42 is merged - for any new notes for the documentation, let's create another issue for a second pass.
