### ISSUE TITLE
Add additional text to the welcome message

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/greetbot#87]
@wuworkshop saw this neat message @billglover wrote to a new member on Slack:

```
If you have any questions about the community or the project or want to talk to an admin, feel free to ask about it in #codebuddies-meta. It’s where discussions related to our community happen.
```

Let's add it to the welcome message. Do any new contributors want to work on it?

**Comment by BethanyG** [comment]
This is already part of the welcome message.  Please see attached screegrab.

**Comment by BethanyG** [comment]
Well -- that didn't go through.  Please see the two attached screengrabs below.  The verbiage he used was from the existing welcome messages - no edits required...unless we'd also like to add a note about API keys or other code changes??

![screen shot 2018-06-27 at 1 40 44 pm](https://user-images.githubusercontent.com/5923094/41998492-c352c948-7a0f-11e8-9d21-3d6eaa9af832.png)
![screen shot 2018-06-27 at 1 40 44 pm](https://user-images.githubusercontent.com/5923094/41998494-c436889a-7a0f-11e8-9f86-54761b81cbf8.png)

**Comment by BethanyG** [comment]
If so...proposals on wording?

**Comment by lpatmo** [comment]
Draft: 

If you have any questions about the community or the project or want to talk to an admin, feel free to ask about it in #codebuddies-meta. It’s where discussions related to our community happen.

If you'd like to add a new integration to the Slack, please ask in the #codebuddies-meta channel as well! Because CodeBuddies is on a free plan, the number of new Slack apps we can integrate is limited, so we would need to choose our integrations wisely.

**Comment by wuworkshop** [comment]
@lpatmo I just now noticed you misunderstood the thing I said in the Slack conversation. Bill said:

> When talking to people about denying requests for tokens/plugins I’ve asked them to treat them as features and raise a request for discussion.

And I suggested that we add something along those lines to this part of the Welcome message:

>If you have any questions about the community or the project or want to talk to an admin, feel free to ask about it in #codebuddies-meta. It’s where discussions related to our community happen.

**Comment by lpatmo** [comment]
@wuworkshop Proof that I was truly sleep-deprived yesterday! Here's a revised draft:

> If you have any questions about the community or the project or want to talk to an admin, feel free to ask about it in #codebuddies-meta. It’s where discussions related to our community happen. If you'd like to add a new integration to the Slack, please treat it as a feature and raise a request for discussion by filing a Github issue.

Something like that?

**Comment by peoray** [comment]
Okay, so I wanna do this but it seems no consensus has been reached on what the message should be?

**Comment by wuworkshop** [comment]
Hmm... 🤔  I think I actually prefer @lpatmo's first draft.

>If you have any questions about the community or the project or want to talk to an admin, feel free to ask about it in #codebuddies-meta. It’s where discussions related to our community happen.
>
>If you'd like to add a new integration to the Slack, please ask in the #codebuddies-meta channel as well! Because CodeBuddies is on a free plan, the number of new Slack apps we can integrate is limited, so we would need to choose our integrations wisely.

I think it makes more sense for the person to ask in the Slack first about Slack integrations.

**Comment by lpatmo** [comment]
Thanks @wuworkshop! @peoray Is that enough for you to get started? Let us know if you run into any questions.

**Comment by peoray** [comment]
@lpatmo Yeah, let me get started. Wish me luck, first OSS contribution :fearful:

**Comment by peoray** [comment]
Okay, so I' having issues as to how to set up locally. I get it that I have to fork this repo https://github.com/codebuddies/greetbot, then set it up locally, but no detailed instruction was given as to how to do this

**Comment by stain88** [comment]
Have you been through the [wiki](https://github.com/codebuddies/greetbot/wiki/Setup-Greetbot-in-your-Slack-Workspace)? Which step did you get stuck at?

**Comment by peoray** [comment]
It seems I will have to create a slack workspace?

**Comment by peoray** [comment]
So I encountered an error on the events subscriptions stage. Seems like my URL didn't respond with the value of the challenge parameter. 

After running the two commands given: `npm run start:dev-server` and `npm run start:dev-tunnel` in two separate instances of my terminal, I got some errors thrown at me

Also, my URL https://peoray.localtunnel.me/ shows a 404 page

**Comment by peoray** [comment]
For some reason, my changes are not working!

I included the new text but no change on the message displayed by the bot

**Comment by stain88** [comment]
I'll have to defer to @BethanyG on how the welcome message actually works. But if you want, throw up a new Pull Request, and we can review what you've done
