### ISSUE TITLE
Add `/message` or `/flag` or `@greetbot flag` action for  Users

### ISSUE THREAD

**Issue by BethanyG** [codebuddiesdotorg/greetbot#91]
Add a `/message` or `/flag` action so that users can flag concerning/bullying/inappropriate messages and have them sent to #admin for action.  A nice to have would be an interactive event-type message that would allow a user to give a reason or comment along with the flagged message.

**Comment by stain88** [comment]
@lpatmo @angelocordon @billglover 
Can we close this in favour of BuddyBot?

**Comment by lpatmo** [comment]
Thanks, makes sense!
