### ISSUE TITLE
Change out link in the welcome text

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/greetbot#94]
At the moment, we link to https://codebuddies.slack.com/files/U0G92F4J0/F8VRAGD0S/CodeBuddies_Slack_Etiquette_for_General_Members in the welcome text.

Non-admin users aren't able to see this link, unfortunately. We've cross-posted the same content (with additional guidelines about promoted posts) to https://codebuddies.org/slack. 

TODO: 
- Change out https://codebuddies.slack.com/files/U0G92F4J0/F8VRAGD0S/CodeBuddies_Slack_Etiquette_for_General_Members to be https://codebuddies.org/slack

The file to edit: https://github.com/codebuddies/greetbot/blob/9fb6a4a0c105d0f61f0d89e8b1778912dad2828e/src/app/routes/endpoints/events/initial.js

**Comment by peoray** [comment]
@lpatmo If no one has indicated interest, I'd love to work on this.

**Comment by lpatmo** [comment]
Marked this as 'claimed' for you. 

Btw, are you interested in participating in Hacktoberfest this year? If you open up the PR between October 1st - October 31st, it can count towards one of the five PRs you need to get a free t-shirt from the Hacktoberfest organizers. :)

**Comment by peoray** [comment]
Lol, that's tempting.

**Comment by cfanoulis** [comment]
Hey, is this being worked on? Hacktoberfest site reccomended this repo, and it's JavaScript, so I would love ~~to steal it~~ to take this on if the other user isn't interested still

**Comment by stain88** [comment]
This is claimed by @peoray.
If nothing has been done by next week, it will be marked as unclaimed @cfanoulis

**Comment by DSerp** [comment]
#97 Leaving it here in case the claimer doesn't want to do it anymore.

**Comment by lpatmo** [comment]
Thanks @peoray, @Serpa88, and @stain88!
